import { type OpsCase } from '@/lib/sample-data/operations-dashboard-data';

export interface ExportOptions {
  format: 'csv' | 'pdf' | 'excel';
  filename?: string;
  columns?: string[];
  includeHeaders?: boolean;
}

export class ExportManager {
  static async exportCases(cases: OpsCase[], options: ExportOptions): Promise<void> {
    const { format, filename = 'vetting-cases', columns, includeHeaders = true } = options;

    switch (format) {
      case 'csv':
        await this.exportToCSV(cases, filename, columns, includeHeaders);
        break;
      case 'pdf':
        await this.exportToPDF(cases, filename);
        break;
      case 'excel':
        await this.exportToExcel(cases, filename, columns, includeHeaders);
        break;
      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  }

  private static async exportToCSV(
    cases: OpsCase[], 
    filename: string, 
    columns?: string[], 
    includeHeaders: boolean = true
  ): Promise<void> {
    const headers = columns || [
      'Case Number', 'Entity Name', 'Entity Type', 'Status', 'Priority', 
      'Progress', 'Assigned Officer', 'Primary Provider', 'Initiated Date', 
      'Est. Completion Date', 'Est. Cost', 'Is Overdue'
    ];

    const csvData = cases.map(case_ => [
      case_.caseNumber,
      case_.entity.name,
      case_.entity.type,
      case_.status,
      case_.priority,
      `${case_.progress}%`,
      case_.assignedOfficer.name,
      case_.primaryProvider,
      case_.initiatedDate,
      case_.estCompletionDate,
      `R ${case_.estCost.toLocaleString()}`,
      case_.isOverdue ? 'Yes' : 'No'
    ]);

    let csvContent = '';
    
    if (includeHeaders) {
      csvContent += headers.join(',') + '\n';
    }

    csvContent += csvData.map(row => 
      row.map(cell => `"${cell}"`).join(',')
    ).join('\n');

    this.downloadFile(csvContent, `${filename}.csv`, 'text/csv');
  }

  private static async exportToPDF(cases: OpsCase[], filename: string): Promise<void> {
    // Create a comprehensive PDF report
    // Generate PDF content
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const pdfContent = this.generatePDFContent(cases);
    
    // For demo purposes, we'll create a simple text-based PDF
    // In production, you'd use a library like jsPDF or Puppeteer
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Vetting Cases Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          .header { text-align: center; margin-bottom: 30px; }
          .case { margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; }
          .case-header { font-weight: bold; margin-bottom: 10px; }
          .case-details { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
          .overdue { color: #dc2626; font-weight: bold; }
          .completed { color: #16a34a; }
          @media print { body { margin: 0; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>VettPro Operations Dashboard</h1>
          <h2>Vetting Cases Report</h2>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
          <p>Total Cases: ${cases.length}</p>
        </div>
        
        ${cases.map(case_ => `
          <div class="case">
            <div class="case-header ${case_.isOverdue ? 'overdue' : ''}">
              ${case_.caseNumber} - ${case_.entity.name}
            </div>
            <div class="case-details">
              <div><strong>Status:</strong> ${case_.status}</div>
              <div><strong>Priority:</strong> ${case_.priority}</div>
              <div><strong>Progress:</strong> ${case_.progress}%</div>
              <div><strong>Assigned Officer:</strong> ${case_.assignedOfficer.name}</div>
              <div><strong>Entity Type:</strong> ${case_.entity.type}</div>
              <div><strong>Primary Provider:</strong> ${case_.primaryProvider}</div>
              <div><strong>Initiated:</strong> ${new Date(case_.initiatedDate).toLocaleDateString()}</div>
              <div><strong>Est. Completion:</strong> ${new Date(case_.estCompletionDate).toLocaleDateString()}</div>
              <div><strong>Est. Cost:</strong> R ${case_.estCost.toLocaleString()}</div>
              <div><strong>Overdue:</strong> ${case_.isOverdue ? 'Yes' : 'No'}</div>
            </div>
          </div>
        `).join('')}
        
        <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #666;">
          Report generated by VettPro Operations Dashboard
        </div>
      </body>
      </html>
    `;

    // Create and trigger download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.html`;
    link.click();
    URL.revokeObjectURL(url);
  }

  private static async exportToExcel(
    cases: OpsCase[], 
    filename: string, 
    columns?: string[], 
    includeHeaders: boolean = true
  ): Promise<void> {
    // For demo purposes, we'll create a CSV with .xlsx extension
    // In production, you'd use a library like SheetJS or ExcelJS
    const headers = columns || [
      'Case Number', 'Entity Name', 'Entity Type', 'Status', 'Priority', 
      'Progress', 'Assigned Officer', 'Primary Provider', 'Initiated Date', 
      'Est. Completion Date', 'Est. Cost', 'Is Overdue'
    ];

    // Create Excel-compatible CSV with additional formatting
    const excelData = cases.map(case_ => [
      case_.caseNumber,
      case_.entity.name,
      case_.entity.type,
      case_.status,
      case_.priority,
      case_.progress / 100, // Excel percentage format
      case_.assignedOfficer.name,
      case_.primaryProvider,
      case_.initiatedDate,
      case_.estCompletionDate,
      case_.estCost,
      case_.isOverdue
    ]);

    let excelContent = '';
    
    if (includeHeaders) {
      excelContent += headers.join('\t') + '\n';
    }

    excelContent += excelData.map(row => row.join('\t')).join('\n');

    this.downloadFile(excelContent, `${filename}.xlsx`, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  }

  private static generatePDFContent(cases: OpsCase[]): string {
    const totalCases = cases.length;
    const completedCases = cases.filter(c => c.status === 'Complete').length;
    const overdueCases = cases.filter(c => c.isOverdue).length;
    const pendingConsent = cases.filter(c => c.status === 'Consent Pending').length;

    return `
      VettPro Operations Dashboard - Cases Report
      Generated: ${new Date().toLocaleDateString()}
      
      Summary:
      - Total Cases: ${totalCases}
      - Completed: ${completedCases}
      - Overdue: ${overdueCases}
      - Pending Consent: ${pendingConsent}
      
      ${cases.map(case_ => `
        Case: ${case_.caseNumber}
        Entity: ${case_.entity.name} (${case_.entity.type})
        Status: ${case_.status}
        Priority: ${case_.priority}
        Progress: ${case_.progress}%
        Officer: ${case_.assignedOfficer.name}
        Provider: ${case_.primaryProvider}
        Initiated: ${case_.initiatedDate}
        Due: ${case_.estCompletionDate}
        Cost: R ${case_.estCost.toLocaleString()}
        Overdue: ${case_.isOverdue ? 'Yes' : 'No'}
        ---
      `).join('')}
    `;
  }

  private static downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  static getAvailableFormats(): Array<{ value: string; label: string }> {
    return [
      { value: 'csv', label: 'CSV (Comma Separated Values)' },
      { value: 'pdf', label: 'PDF (Portable Document Format)' },
      { value: 'excel', label: 'Excel (Microsoft Excel)' }
    ];
  }

  static getAvailableColumns(): Array<{ value: string; label: string }> {
    return [
      { value: 'caseNumber', label: 'Case Number' },
      { value: 'entityName', label: 'Entity Name' },
      { value: 'entityType', label: 'Entity Type' },
      { value: 'status', label: 'Status' },
      { value: 'priority', label: 'Priority' },
      { value: 'progress', label: 'Progress' },
      { value: 'assignedOfficer', label: 'Assigned Officer' },
      { value: 'primaryProvider', label: 'Primary Provider' },
      { value: 'initiatedDate', label: 'Initiated Date' },
      { value: 'estCompletionDate', label: 'Est. Completion Date' },
      { value: 'estCost', label: 'Est. Cost' },
      { value: 'isOverdue', label: 'Is Overdue' }
    ];
  }
}